# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.3
_src_path: https://github.com/trobz/trobz-python-template.git
author_email: doanminhtri8183@gmail.com
author_username: trisdoan
enable_github_action: true
package_name: odoo_addons_path
project_description: Create the ultimate Odoo addons_path constructor
project_name: odoo-addons-path
publish_to_pypi: true
repository_name: odoo-addons-path
repository_namespace: trobz
